export const STRINGS = {
  title: 'Регистрация',
  registration: 'Зарегистрироваться',
  name: 'Имя',
  email: 'Электронная почта',
  password: 'Пароль',
  confirmPass: 'Подтвердите пароль',
  nameExample: 'Введите имя, например: Артур',
  emailExample: 'example@mail.ru',
  hiddenPass: '******',
  logIn: 'Войти',
  registerError: 'Ошибка регистрации',
  loginError: 'Неверный логин или пароль',
  hasAccount: 'Уже есть аккаунт?',
  noAccount: 'Нет аккаунта?',
  exit: 'Выход',
  back: 'Назад',
  ourTeam: 'Наша команда',
};
